# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

alfaromeo = Brand.create(name: "Alfa Romeo", origin: "Italy")
astonmartin = Brand.create(name: "Aston Martin", origin: "UK")
audi = Brand.create(name: "Audi", origin: "Germany")
bentley = Brand.create(name: "Bentley", origin: "UK")
bmw = Brand.create(name: "BMW", origin: "Germany")
bugatti = Brand.create(name: "Bugatti", origin: "France")
cadillac = Brand.create(name: "Cadillac", origin: "USA")
chevrolet = Brand.create(name: "Chevrolet", origin: "USA")
chrysler = Brand.create(name: "Chrysler", origin: "USA")
dodge = Brand.create(name: "Dodge", origin: "USA")
ferrari = Brand.create(name: "Ferrari", origin: "Italy")
fiat = Brand.create(name: "Fiat", origin: "Italy")
ford = Brand.create(name: "Ford", origin: "USA")
gmc = Brand.create(name: "GMC", origin: "USA")
honda = Brand.create(name: "Honda", origin: "Japan")
hyundai = Brand.create(name: "Hyundai", origin: "South Korea")
infiniti = Brand.create(name: "Infiniti", origin: "Japan")
jaguar = Brand.create(name: "Jaguar", origin: "UK")
jeep = Brand.create(name: "Jeep", origin: "USA")
kia = Brand.create(name: "Kia", origin: "South Korea")
koenigsegg = Brand.create(name: "Koenigsegg", origin: "Sweden")
lamborghini = Brand.create(name: "Lamborghini", origin: "Italy")
landrover = Brand.create(name: "Land Rover", origin: "UK")
lexus = Brand.create(name: "Lexus", origin: "Japan")
maserati = Brand.create(name: "Maserati", origin: "Italy")
mazda = Brand.create(name: "Mazda", origin: "Japan")
mclaren = Brand.create(name: "McLaren", origin: "UK")
mercedesbenz = Brand.create(name: "Mercedes Benz", origin: "Germany")
mini = Brand.create(name: "Mini", origin: "UK")
mitsubishi = Brand.create(name: "Mitsubishi", origin: "Japan")
nissan = Brand.create(name: "Nissan", origin: "Japan")
pagani = Brand.create(name: "Pagani", origin: "Italy")
porsche = Brand.create(name: "Porsche", origin: "Germany")
rangerover = Brand.create(name: "Range Rover", origin: "UK")
rollsroyce = Brand.create(name: "Rolls Royce", origin: "UK")
subaru = Brand.create(name: "Subaru", origin: "Japan")
suzuki = Brand.create(name: "Suzuki", origin: "Japan")
tesla = Brand.create(name: "Tesla", origin: "USA")
toyota = Brand.create(name: "Toyota", origin: "Japan")
volkswagen = Brand.create(name: "Volkswagen", origin: "Germany")
volvo = Brand.create(name: "Volvo", origin: "Sweden")

Car.create(name: "", year: "", color: "", mileage: "", image_url: "", brand_id: )
Car.create(name: "", year: "", color: "", mileage: "", image_url: "", brand_id: )
Car.create(name: "", year: "", color: "", mileage: "", image_url: "", brand_id: )
Car.create(name: "", year: "", color: "", mileage: "", image_url: "", brand_id: )